version: '3'
services:
  backend:
    image: node:14
    container_name: backend-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3003:3003'
    command: npm start
    environment:
      NODE_ENV: production
